[general]
# Start Satty in fullscreen mode
fullscreen = true
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "crop"
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "copy-png"
# Exit directly after copy/save action
early-exit = true
